In [2]:
import pandas as pd
data=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv" , sep=";")

In [3]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [4]:
data.shape

(1599, 12)

In [5]:
from sklearn.model_selection import train_test_split
train,test=train_test_split(data)

In [6]:
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1590,6.3,0.550,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.600000,6
1494,6.4,0.310,0.09,1.4,0.066,15.0,28.0,0.99459,3.42,0.70,10.000000,7
437,11.1,0.450,0.73,3.2,0.066,6.0,22.0,0.99860,3.17,0.66,11.200000,6
1136,10.4,0.520,0.45,2.0,0.080,6.0,13.0,0.99774,3.22,0.76,11.400000,6
1174,7.6,0.360,0.31,1.7,0.079,26.0,65.0,0.99716,3.46,0.62,9.500000,6
...,...,...,...,...,...,...,...,...,...,...,...,...
1362,11.6,0.475,0.40,1.4,0.091,6.0,28.0,0.99704,3.07,0.65,10.033333,6
67,6.6,0.705,0.07,1.6,0.076,6.0,15.0,0.99620,3.44,0.58,10.700000,5
836,6.7,0.280,0.28,2.4,0.012,36.0,100.0,0.99064,3.26,0.39,11.700000,7
477,10.4,0.240,0.49,1.8,0.075,6.0,20.0,0.99770,3.18,1.06,11.000000,6
627,8.8,0.600,0.29,2.2,0.098,5.0,15.0,0.99880,3.36,0.49,9.100000,5

In [7]:
test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1007,9.1,0.30,0.34,2.0,0.064,12.0,25.0,0.99516,3.26,0.84,11.7,7
1324,6.7,0.46,0.24,1.7,0.077,18.0,34.0,0.99480,3.39,0.60,10.6,6
1037,7.3,0.91,0.10,1.8,0.074,20.0,56.0,0.99672,3.35,0.56,9.2,5
1246,7.4,0.74,0.07,1.7,0.086,15.0,48.0,0.99502,3.12,0.48,10.0,5
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
27,7.9,0.43,0.21,1.6,0.106,10.0,37.0,0.99660,3.17,0.91,9.5,5
1050,7.1,0.43,0.17,1.8,0.082,27.0,51.0,0.99634,3.49,0.64,10.4,5
976,7.2,0.41,0.30,2.1,0.083,35.0,72.0,0.99700,3.44,0.52,9.4,5
100,8.3,0.61,0.30,2.1,0.084,11.0,50.0,0.99720,3.40,0.61,10.2,6
338,12.4,0.49,0.58,3.0,0.103,28.0,99.0,1.00080,3.16,1.00,11.5,6